class P2PProtocol:
    HANDSHAKE = "HANDSHAKE"
    HANDSHAKE_ACK = "HANDSHAKE_ACK"
    QUERY = "QUERY"
    QUERY_HIT = "QUERY_HIT"
    GET_CHUNK = "GET_CHUNK"
    CHUNK_DATA = "CHUNK_DATA"
    ERROR = "ERROR"